### ISSUE TITLE
Decrypt API returns AAD instead of verifying it

### ISSUE THREAD

**Issue by mykter** [eclipse-keypont/gose#8]
The [example](https://github.com/ThalesIgnite/gose/blob/f9b49f16587af849fe3db60c7a109b604335173c/examples/jwe/jwe.go#L78) for decrypting using a JWE is:
`	plaintext, aad, err := decryptor.Decrypt(jwe)`

This is risky, because the burden is now on the caller to verify the AAD. I see that `AuthenticatedEncryptionKey` has a safer interface - `Open` - which takes the AAD and will return an error unless the AAD matches.

I'm not familiar with this package but my impression is that deprecating the existing Decrypt function and adding a `DecryptCheck(jwe, aad)` or similar would be helpful. (Or bumping the major version and changing the Decrypt API). I don't think there are (valid) use cases where the caller doesn't know the AAD in advance - the only thing a caller should ever do with the returned AAD from Decrypt is check it matches what they expect and discard the plaintext if it doesn't.

**Comment by ProsaicSatsuma** [comment]
So, from a quick look, it seems like what we're doing here is using AAD by way of a custom header field, allowing us to use AAD with compact serialization.

It's a good point, but unless I'm missing something, I think it comes down to the question of whether the verifier knows the AAD up-front. You're right - in most cases, the AAD should be calculated and provided independently by the verifier, but I believe that in the JWE case, the AAD is always contained within the JWE, with no option to provide this from 'outside' the JWE. As to what the AAD would be used for in practice, I've been unable to find any guidance/examples. The normal Open/Seal functions are being used behind the Encrypt/Decrypt interfaces, feeding the aad from the JWE into the AEAD routines.

Given this, I think it's probably fine as is

**Comment by mykter** [comment]
I'm not familiar with JWE but reading the spec it implies to me that if a 'JWE AAD' is supplied, it isn't returned after decryption:
```
16   ...returning the decrypted plaintext and validating the JWE
        Authentication Tag in the manner specified for the algorithm,
        rejecting the input without emitting any decrypted output if the
        JWE Authentication Tag is incorrect.
```
Tried to compare with some other implementations. The Square Go & JS libraries don't return AAD; panva/jose doesn't by default but optionally can.

Given that our API doesn't expose access to the AAD prior to decryption, it doesn't seem to make sense to me that you would ever use it other than in the usual manner of knowing it in advance and needing to verify it was correct. If you needed to learn the value of the AAD, you'd just put it as part of the ciphertext - there's no downside.

So I'm still of the impression that this API encourages dangerous use, specifically AAD being input to an encryption but not being checked on decryption.

**Comment by mykter** [comment]
re: our offline talk, it's not obvious why the AAD exists at all, and it seems likely it won't get used. However in the absence of concrete information on how it might be used we can't rule out needing to retrieve it and process it in some way other than verifying its value matches an already known contextual value.
